Remove timeout from engine, as we now receive network timeouts.
Below demonstrates terminating IB Gateway in the middle of a 'go test
-short'. As shown, error EOF (ie an io.EOF) is detected. Interestingly
IB Gateway sends an ErrorMessage 1100 as it's shutting down, so any
active observers could look for that rather than an engine-level
io.EOF error (which I'll be making available in conjunction with a
planned state channel next up). Of course clients cannot rely solely on
that ErrorMessage, as there might be a network issue or SIGKILL on IB
Gateway (which wouldn't therefore have an opportunity to send the 1100).

3> '9-5-100-0-AAPL-STK--0---SMART-USD--0-'
3< &{15 1} &{DU15083}
3< &{9 1} &{1}
3< &{4 2} &{-1 2104 Market data farm connection is OK:ibdemo}
3< EOF
2014/03/12 11:54:55 3 engine: error EOF
2014/03/12 11:54:55 3 engine: closing connection
--- FAIL: TestContractDetails (30.60 seconds)
        engine_test.go:26: received message '&{-1 2104 Market data farm connection is OK:ibdemo}' of ty
pe '*trade.ErrorMessage'
        engine_test.go:26: received message '&{-1 1100 Connectivity between IB and TWS has been lost.}'
 of type '*trade.ErrorMessage'
        engine_test.go:175: received reply nil
        engine_test.go:180:  (error: 'Timeout waiting')
        engine_test.go:182:
        engine_test.go:126: client 3: cannot receive contract details: Timeout waiting
--- FAIL: TestOptionChainRequest (0.00 seconds)
        engine_test.go:141: cannot connect engine: dial tcp 127.0.0.1:4001: connection refused
--- FAIL: TestInstrument (0.00 seconds)
        instrument_test.go:12: cannot connect engine: dial tcp 127.0.0.1:4001: connection refused
--- FAIL: TestMetadata (0.00 seconds)
        metadata_test.go:12: cannot connect engine: dial tcp 127.0.0.1:4001: connection refused
--- FAIL: TestIncomplete (0.00 seconds)
        metadata_test.go:41: cannot connect engine: dial tcp 127.0.0.1:4001: connection refused